version: '3.8'
services:
  # payment-api:
  #   build: .
  #   ports:
  #     - "8004:8004"

  #   image: payment_api:1.1
  #   depends_on:
  #     - mongodb_container

  mongodb_container:
    image: mongo:latest
    environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
        - "27019:27017"
    volumes:
        - mongodb_data_container:/data/db

volumes:
  mongodb_data_container: