version: "3.8"
  
services:
  db:
    image: postgres:15.0
    container_name: postgres_0.11
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=orders_db

    volumes: 
      - order_volume:/var/lib/postgresql/data
    ports:
      - 5432:5432
    

  rabbitmq3:
    container_name: "rabbitmq3"
    image: rabbitmq:3.8-management-alpine
    environment:
        - RABBITMQ_DEFAULT_USER=myuser
        - RABBITMQ_DEFAULT_PASS=mypassword
    ports:
        # AMQP protocol port
        - '5672:5672'
        # HTTP management UI
        - '15672:15672'



  # order_api:
  #   build: .
  #   image: order_api:0.0.0
  #   restart: always
  #   ports:
  #     - 8000:8000
    

volumes:
  order_volume: