version: "3.8"
  
services:
  order_db:
    platform: linux/amd64
    image: postgres:15.0
    container_name: order_db
    restart: always

    environment:
      - POSTGRES_PASSWORD=order
      - POSTGRES_USER=order
      - POSTGRES_DB=order
    
    ports:
      - 5432:5432

    volumes: 
      - order_volume:/var/lib/postgresql/data
    

  # order_api:
  #   platform: linux/amd64
  #   build: .
  #   image: order_api:0.0.0
  #   restart: always
  #   ports:
  #     - 8000:8000
    

volumes:
  order_volume: