version: '3.8'
services:
  buyer-api:
    build: .
    ports:
      - "8002:8002"

    image: buyer_api:1.17
    depends_on:
      - mongodb_container


  mongodb_container:
    image: mongo:latest
    environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
        - "27018:27017"
    volumes:
        - mongodb_data_container:/data/db

volumes:
  mongodb_data_container:
